version: '3.4'
services:  
  # Backend (Node.js)
  node-backend:
    build: './images/backend/'
    volumes:
      - ./images/backend/:/home/app/
      - /home/app/node_modules
    ports:
      - "5000:5000"
    networks:
      - network-backend
      - network-frontend
    

  # Frontend (Node.js)
  node-frontend:
    build: './images/frontend/'
    volumes:
      - ./images/frontend/:/home/app/
      - /home/app/node_modules
    ports:
      - "8080:8080"
    networks:
      - network-frontend
    environment:
      - BACKEND_SERVER=node-backend
      - BACKEND_PORT=5000
    networks:
      - network-frontend
    depends_on:
      - node-backend

networks:
  network-backend:
    name: backend
    driver: bridge # Bridge ist Docker-Default.
    # internal: true # Wenn internal auf true gesetzt wird, ist das Netzwerk nicht mehr standardmäßig vom Host aufrufbar. Während Development noch hinderlich.
  network-frontend:
    name: frontend
    driver: bridge # Bridge ist Docker-Default.
